"""added imaya code in models.py

Revision ID: 8f024dc400ef
Revises: 9b622854463e
Create Date: 2019-03-27 16:24:33.123983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f024dc400ef'
down_revision = '9b622854463e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('company', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paidDate', sa.String(length=15), nullable=True),
    sa.Column('company', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_detail')
    op.drop_table('payment')
    # ### end Alembic commands ###
