"""tasks

Revision ID: 9b622854463e
Revises: 2129f31651d3
Create Date: 2019-03-19 22:01:12.613046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b622854463e'
down_revision = '2129f31651d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_bill',
    sa.Column('billId', sa.String(length=36), nullable=False),
    sa.Column('accountNumber', sa.String(length=40), nullable=True),
    sa.Column('accountHolder', sa.String(length=120), nullable=True),
    sa.Column('billingAddress', sa.String(length=120), nullable=True),
    sa.Column('usage', sa.String(length=20), nullable=True),
    sa.Column('duePayment', sa.String(length=40), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('billId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utility_bill')
    # ### end Alembic commands ###
